### PR TITLE
Added login page and header component

### PR DESCRIPTION
**Pull request by vanshika-dargan-18**
@dnagegowda2 @cbug09 
cc: @pratikjoshivonage 

Screenshot 2024-12-19 at 3 24 22 PM
Screenshot 2024-12-19 at 3 24 11 PM

### CODE REVIEW

**Review by dnagegowda2 — APPROVED** [review]
Move Ahead!

**Comment by pratikjoshivonage** [comment]
@vanshika-dargan-18 looks good 
1. can you use Reformat code option for folder /components
2. Can you upload screenshot of UI as image in pull request description?

**Review by cbug09 — APPROVED** [review]
Good To Go

**Comment by pratikjoshivonage** [comment]
image
in next p.r. we can have different url after user logs in something like like localhost:8081/dashboard when user lands on dashboard

**Pull request merged**
