### PR TITLE
chore: remove .idea directory

### PR DESCRIPTION
**Pull request by vanshika-dargan-18**
Task Overview:

Removed unnecessary .idea directory from git

### CODE REVIEW

**Comment by malaypandey98** [comment]
@vanshika-dargan-18 , this PR also contains changes except .idea folder removal. Please fix this.

**Review by malaypandey98 — COMMENTED** [review]
@vanshika-dargan-18 , this PR also contains changes except .idea folder removal. Please fix this.

**Comment by vanshika-dargan-18** [comment]
> @vanshika-dargan-18 , this PR also contains changes except .idea folder removal. Please fix this.

@malaypandey98 I accidently checked out from my previous branch, now I have rebased current branch to main so I guess it should be fine.

**Comment by malaypandey98** [comment]
> > @vanshika-dargan-18 , this PR also contains changes except .idea folder removal. Please fix this.
> 
> @malaypandey98 I accidently checked out from my previous branch, now I have rebased current branch to main so I guess it should be fine.

sure, it good now. Also ask for re-review once u ave resolved the review comment.
Use this icon here, 
Screenshot 2024-12-24 at 4 48 15 PM

**Review by malaypandey98 — APPROVED** [review]

**Review by Dys-Mn11 — APPROVED** [review]

**Review by Shubham-rajput09 — APPROVED** [review]
good

**Pull request merged**
